---
# defaults file for sou_podman

# haproxy
haproxy_id: haproxy
haproxy_port_bind: 8443:8443
haproxy_path: /containers_vols/haproxy

# grafana
grafana_id: grafana
grafana_port_bind: 3000:3000
grafana_path: /containers_vols/grafana
grafana_domain: haproxy.local
grafana_relative_url: grafana
grafana_backend: 192.168.56.12:3000

# prometheus
prometheus_id: prometheus
prometheus_port_bind: 9090:9090
prometheus_path: /containers_vols/prometheus
prometheus_backend: 192.168.56.12:9090